"""Render docs/data-dictionary.md from the code, so the documentation cannot drift from the data.

    python -m psim.docs            # rewrite docs/data-dictionary.md
    python -m psim.docs --check    # exit 1 if the committed file is stale (used by the tests)
"""
from __future__ import annotations

import argparse
from pathlib import Path

from . import config as cfg
from .generate import COLUMNS

DOC_PATH = Path("docs/data-dictionary.md")

COLUMN_DOCS = {
    "record_id": ("integer", "Unique row number."),
    "campaign_id": ("text", "Simulation campaign, C1 to C6 (one per month, April to September 2026)."),
    "send_date": ("date", "Date the simulated phishing email was sent (ISO 8601)."),
    "lure_theme": ("text", "What the simulated email pretended to be."),
    "employee_id": ("text", "Pseudonymous employee ID, stable across campaigns."),
    "department": ("text", "Employee's department."),
    "tenure_band": ("text", "Length of service when the programme started: under_1y, 1_to_3y or over_3y."),
    "nudge_type": ("text", "Behavioural nudge shown with this email. Randomly assigned; `none` is the control."),
    "prior_exposures_to_nudge": (
        "integer",
        "How many earlier campaigns this employee saw this same nudge in (0 on first sight).",
    ),
    "clicked": ("0 or 1", "1 if the employee clicked the link in the simulated email."),
    "reported": ("0 or 1", "1 if the employee reported the email as suspicious through the report button."),
    "outcome": (
        "text",
        "`no_action`, `clicked_only`, `reported_only` or `clicked_and_reported`. Derived from the two flags.",
    ),
    "minutes_to_click": ("number", "Minutes from sending to the click. Blank if not clicked."),
    "minutes_to_report": (
        "number",
        "Minutes from sending to the report. Blank if not reported. Always at or after the click when both happened.",
    ),
}

MODELLED = [
    "Departments differ in how readily they click and report, and in how they respond to each nudge.",
    "Individuals differ persistently. A minority account for most clicks, and people who click readily "
    "tend to report less.",
    "Newer staff click more and report less than long-serving staff.",
    "Lures differ in difficulty, and a lure that fits a department's work (an invoice for Finance) "
    "raises its click rate.",
    "Awareness grows over the programme: clicks drift down and reports drift up.",
    "Someone who has just clicked is less likely to go on to report.",
    "Nudges lose some of their effect on repeat exposure (habituation). With about one exposure to each "
    "nudge per person across six campaigns, this is too faint to see at this sample size.",
]

NOT_MODELLED = [
    "Delivery failures, opens and credential submission or attachment opening after a click.",
    "Leavers and joiners during the programme, or training delivered between campaigns.",
    "Time-of-day and day-of-week effects, or people reporting an email they never saw.",
    "Reports of genuine emails (false positives) and the workload they create for the security team.",
]


def _table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def render() -> str:
    assert list(COLUMN_DOCS) == COLUMNS, "COLUMN_DOCS must list the CSV columns in order"
    employees = sum(d["headcount"] for d in cfg.DEPARTMENTS.values())
    rows = employees * len(cfg.CAMPAIGNS)
    smallest = min(d["headcount"] for d in cfg.DEPARTMENTS.values())
    largest = max(d["headcount"] for d in cfg.DEPARTMENTS.values())
    per_arm = len(cfg.CAMPAIGNS) / len(cfg.NUDGES)

    parts = [
        "# Data dictionary",
        "<!-- Generated by `python -m psim.docs` from psim/config.py. Do not edit by hand. -->",
        f"`data/phishing_sim_events.csv` has {rows:,} rows: one per employee per campaign "
        f"({employees:,} employees, {len(cfg.CAMPAIGNS)} monthly campaigns). It describes a fictional "
        "organisation. No real people or messages are involved.",
        "## Columns",
        _table(
            ["Column", "Type", "Description"],
            [[f"`{c}`", COLUMN_DOCS[c][0], COLUMN_DOCS[c][1]] for c in COLUMNS],
        ),
        "## How to compute the rates",
        "- **Click rate** is the mean of `clicked` over the rows in a group. **Report rate** is the mean of "
        "`reported`. Every email counts as delivered.\n"
        "- The two are not exclusive. An employee can click and then report (`clicked_and_reported`), so "
        "the rates do not add up to a total.\n"
        "- Group by `nudge_type` for the nudge comparison, by `department` for the department view, and by "
        "both for the heatmap. Treat small cells with care (see below).",
        "## Nudge types",
        _table(
            ["`nudge_type`", "Label", "Mechanism"],
            [[f"`{k}`", v["label"], v["mechanism"]] for k, v in cfg.NUDGES.items()],
        ),
        "## Departments",
        _table(
            ["Department", "Employees"],
            [[name, str(spec["headcount"])] for name, spec in cfg.DEPARTMENTS.items()],
        ),
        "## Campaigns",
        _table(
            ["`campaign_id`", "`send_date`", "`lure_theme`"],
            [[c["id"], c["date"], c["lure"]] for c in cfg.CAMPAIGNS],
        ),
        "## Randomisation and sample size",
        "Within each department, every campaign deals the nudges out evenly to a shuffled list of employees "
        "(block randomisation), so each arm is balanced by department and a comparison between nudge types is "
        "fair by design. The same employee meets different nudges in different campaigns.\n\n"
        f"The consequence is small cells. A department with {smallest} employees has about "
        f"{smallest * per_arm:.0f} rows per nudge, and the largest ({largest}) about {largest * per_arm:.0f}. "
        "A department-by-nudge heatmap built on this data should show the number of rows and an interval, "
        "or it will present noise as a finding.",
        "## What the generator puts in",
        "The sizes of all effects are in `data/assumptions.json` (and `psim/config.py`). In words:\n\n"
        + "\n".join(f"- {m}" for m in MODELLED),
        "## What it leaves out",
        "\n".join(f"- {m}" for m in NOT_MODELLED),
    ]
    return "\n\n".join(parts) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is out of date")
    args = parser.parse_args(argv)

    text = render()
    if args.check:
        current = DOC_PATH.read_text(encoding="utf-8") if DOC_PATH.exists() else ""
        if current != text:
            print(f"{DOC_PATH} is out of date: run python -m psim.docs")
            return 1
        print(f"{DOC_PATH} is up to date")
        return 0
    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
